version: '3'
services:
    mongo-db:
        container_name: mongo-db
        image: mongo:latest
        ports:
            - 27017:27017
        expose:
            - 27017
    publishing-app:
        container_name: publishing-app
        image: guzevdev/pet-proj-publishing:latest
        ports:
            - 8080:8080
        environment:
            PETPROJ_MAIL_HOST: ${PETPROJ_MAIL_HOST}
            PETPROJ_MAIL_PORT: ${PETPROJ_MAIL_PORT}
            PETPROJ_MAIL_USERNAME: ${PETPROJ_MAIL_USERNAME}
            PETPROJ_MAIL_PASSWORD: ${PETPROJ_MAIL_PASSWORD}
        depends_on:
            - mongo-db